apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hr-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Give Mongo 1 Gigabyte of permanent storage
