---
- name: Configure EKS Cluster (Install Helm & Argo CD)
  hosts: bastion
  become: yes
  tasks:
    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0700'

    - name: Execute Helm installation script
      command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

    - name: Create namespace for Argo CD
      command: kubectl create namespace argocd
      register: create_ns
      failed_when: 
        - create_ns.rc != 0 
        - '"AlreadyExists" not in create_ns.stderr'
      changed_when: create_ns.rc == 0

    - name: Install Argo CD into EKS Cluster
      command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      register: install_argo
      changed_when: '"created" in install_argo.stdout or "configured" in install_argo.stdout'
