[bastion]
# Add your Bastion Host IP here
# bastion.hr-platform.com ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[kube_nodes]
# Add bare-metal or EC2 Node IPs if managing cluster manually (not needed if using EKS Managed Nodes)

[all:vars]
ansible_python_interpreter=/usr/bin/python3
