apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

# In Dev, we only want 1 replica (server) running to save money!
patches:
  - target:
      kind: Deployment
      name: hr-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: hr-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
